name: Waka Readme

on:
  schedule:
    # Runs every day at 12:00 AM UTC (8:00 AM Philippine Time)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Customization flags
          SHOW_OS: "True"
          SHOW_PROJECTS: "True" 
          SHOW_TIMEZONE: "True"
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False" # Set to True if you want lines of code chart
          SHOW_LINES_OF_CODE: "False" # Heavy operation, set to True if needed
          SHOW_PROFILE_VIEWS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          
          # Customization options
          LOCALE: "en"
          COMMIT_MESSAGE: "📊 Updated with Dev Metrics"
          SECTION_NAME: "waka"
          
          # Progress bar symbol (1, 2, or 3)
          SYMBOL_VERSION: "1"
          
          # Repositories to ignore (comma-separated)
          # IGNORED_REPOS: "repo1,repo2"
          
          # Date format for updated date
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          
          # Commit settings
          COMMIT_BY_ME: "False"
          # COMMIT_USERNAME: "readme-bot"
          # COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
